baseURL: "https://mschick94.github.io" 
title: Moritz-Maria von Igelfeld
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Talks
          url: talks/
          weight: 3
        - name: CV
          url: cv.pdf
          weight: 4

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","teaching","talks"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Professor Dr von Igelfeld
          subtitle: "I am a Professor in the Institute of Romance Philology at the University of Regensburg, Germany. My research focuses on Portuguese irregular verbs. I was a doctoral student of Professor Dr Dieter Vogelsang in Munich, and later a second assistant of Professor Walter Schoeffler-Henschell at the University of Wiesbaden."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Talks
              url: talks/
            - name: CV
              url: cv.pdf

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:user@gmail.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=user
        - name: GitHub
          url: https://github.com/user

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2