baseURL: "https://mschick94.github.io" 
title: Manuel Schick
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Talks
          url: talks/
          weight: 3
        - name: CV
          url: cv.pdf
          weight: 4

params:
    description: "This website hosts Manuel Schick's research, teaching materials, talks, and curriculum vitae."
    author: Manuel Schick
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","teaching","talks"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "Manuel Schick"
          subtitle: "I am a PhD Candidate at Heidelberg University and a Postdoctoral Researcher at the Vrije Universiteit Amsterdam. My research interests comprise econometrics, macroeconometrics, time-series analysis, and empirical finance. I hold a Master's degree in Economics and Finance from the University of Tübingen, where I gained work experience in economic research as a student assistant at the Institute of Applied Economic Research (IAW)."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Talks
              url: talks/
            - name: CV
              url: cv.pdf

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:manuel.schick@awi.uni-heidelberg.de
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=L2-YYy4AAAAJ&hl=de&oi=ao
        - name: Ssrn
          url: https://ssrn.com/author=DEINE-ID
        - name: GitHub
          url: https://github.com/user
        - name: LinkedIn
          url: https://de.linkedin.com/in/manuel-schick-63a314310/de

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Manuel Schick"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2